# (c) @AbirHasan2005

from bot.configs import Config

BOT_TOKEN = Config.BOT_TOKEN
TG_USER_SESSION = Config.TG_USER_SESSION
SESSION_NAME = "DMCA_DelBot"
API_ID = Config.API_ID
API_HASH = Config.API_HASH
DATABASE_URL = Config.DATABASE_URL
LOGS_CHANNEL = Config.LOGS_CHANNEL
UPDATES_CHANNEL = Config.UPDATES_CHANNEL
START_TEXT = Config.START_TEXT
HELP_TEXT = Config.HELP_TEXT
ABOUT_TEXT = Config.ABOUT_TEXT
ADMIN = Config.ADMIN
BROADCAST_AS_COPY = Config.BROADCAST_AS_COPY
